name: biscript-yolo 
channels: 
"  - pytorch" 
"  - conda-forge" 
"  - defaults" 
dependencies: 
"  - python=3.8" 
"  - pip" 
"  - pytorch" 
"  - torchvision" 
"  - pip:" 
"    - ultralytics" 
"    - opencv-python" 
"    - Pillow" 
