name: BiScript-YOLO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install ultralytics opencv-python pillow numpy
        
    - name: Run tests
      run: |
        python -c "import torch; print('PyTorch installed')"
        python -c "import ultralytics; print('Ultralytics installed')"
        echo "All tests passed!"